// 
// Decompiled by Procyon v0.6.0
// 

package net.labymod.autogen.core.lss;

import net.labymod.autogen.core.lss.properties.direct.LazyGridWidgetTestActivityDummyWidgetDirectPropertyValueAccessor;
import net.labymod.core.test.widget.LazyGridWidgetTestActivity;
import net.labymod.autogen.core.lss.properties.direct.StyleOrderTestWidgetDirectPropertyValueAccessor;
import net.labymod.core.test.styleorder.StyleOrderTestWidget;
import net.labymod.autogen.core.lss.properties.direct.AddonRecommendationPacketHandlerAddonRecommendationItemWidgetDirectPropertyValueAccessor;
import net.labymod.core.main.serverapi.protocol.neo.handler.game.moderation.AddonRecommendationPacketHandler;
import net.labymod.autogen.core.lss.properties.direct.SprayWheelWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.spray.SprayWheelWidget;
import net.labymod.autogen.core.lss.properties.direct.AccountWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.account.AccountWidget;
import net.labymod.autogen.core.lss.properties.direct.AccountPopupEntryWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.account.AccountPopupEntryWidget;
import net.labymod.autogen.core.lss.properties.direct.RevisionPopupWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.RevisionPopupWidget;
import net.labymod.autogen.core.lss.properties.direct.EmoteSegmentWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.emote.EmoteSegmentWidget;
import net.labymod.autogen.core.lss.properties.direct.EmoteWheelWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.emote.EmoteWheelWidget;
import net.labymod.autogen.core.lss.properties.direct.WheelWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.core.lss.properties.direct.NavigationListWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.navigation.NavigationListWidget;
import net.labymod.autogen.core.lss.properties.direct.HudWidgetWindowWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.hud.window.HudWidgetWindowWidget;
import net.labymod.autogen.core.lss.properties.direct.HudWidgetTypeInfoWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.hud.window.grid.HudWidgetTypeInfoWidget;
import net.labymod.autogen.core.lss.properties.direct.HudWidgetTilesGridWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.hud.window.grid.HudWidgetTilesGridWidget;
import net.labymod.autogen.core.lss.properties.direct.HudWidgetInteractionWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.hud.HudWidgetInteractionWidget;
import net.labymod.autogen.core.lss.properties.direct.HudWidgetRendererWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.hud.HudWidgetRendererWidget;
import net.labymod.autogen.core.lss.properties.direct.GlobalSettingWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.hud.renderer.GlobalSettingWidget;
import net.labymod.autogen.core.lss.properties.direct.ScreenshotTileWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.screenshot.timeline.ScreenshotTileWidget;
import net.labymod.autogen.core.lss.properties.direct.ScreenshotContainerWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.screenshot.timeline.ScreenshotContainerWidget;
import net.labymod.autogen.core.lss.properties.direct.ScreenshotTimelineWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.screenshot.timeline.ScreenshotTimelineWidget;
import net.labymod.autogen.core.lss.properties.direct.ScreenshotScrollbarWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.screenshot.timeline.ScreenshotScrollbarWidget;
import net.labymod.autogen.core.lss.properties.direct.ScreenshotSectionWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.screenshot.timeline.ScreenshotSectionWidget;
import net.labymod.autogen.core.lss.properties.direct.ImageViewerWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.screenshot.viewer.ImageViewerWidget;
import net.labymod.autogen.core.lss.properties.direct.ScreenshotViewerWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.screenshot.viewer.ScreenshotViewerWidget;
import net.labymod.autogen.core.lss.properties.direct.PublicServerInfoWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.multiplayer.PublicServerInfoWidget;
import net.labymod.autogen.core.lss.properties.direct.StorageServerInfoWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.multiplayer.StorageServerInfoWidget;
import net.labymod.autogen.core.lss.properties.direct.DirectConnectServerInfoWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.multiplayer.DirectConnectServerInfoWidget;
import net.labymod.autogen.core.lss.properties.direct.LiveLabyNetServerInfoWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.multiplayer.LiveLabyNetServerInfoWidget;
import net.labymod.autogen.core.lss.properties.direct.LabyNetServerInfoWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.multiplayer.LabyNetServerInfoWidget;
import net.labymod.autogen.core.lss.properties.direct.LanServerInfoWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.multiplayer.LanServerInfoWidget;
import net.labymod.autogen.core.lss.properties.direct.ServerInfoWidgetDirectPropertyValueAccessor;
import net.labymod.api.client.gui.screen.widget.widgets.activity.multiplayer.ServerInfoWidget;
import net.labymod.autogen.core.lss.properties.direct.ServerFolderWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.multiplayer.ServerFolderWidget;
import net.labymod.autogen.core.lss.properties.direct.ServerEntryWidgetDirectPropertyValueAccessor;
import net.labymod.api.client.gui.screen.widget.widgets.activity.multiplayer.ServerEntryWidget;
import net.labymod.autogen.core.lss.properties.direct.InstalledItemWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.store.InstalledItemWidget;
import net.labymod.autogen.core.lss.properties.direct.ReviewWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.store.profile.ReviewWidget;
import net.labymod.autogen.core.lss.properties.direct.DescriptionWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.store.profile.DescriptionWidget;
import net.labymod.autogen.core.lss.properties.direct.ProfileInfoWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.store.profile.ProfileInfoWidget;
import net.labymod.autogen.core.lss.properties.direct.ChangelogWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.store.profile.ChangelogWidget;
import net.labymod.autogen.core.lss.properties.direct.StoreItemWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.store.StoreItemWidget;
import net.labymod.autogen.core.lss.properties.direct.GradientWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.store.GradientWidget;
import net.labymod.autogen.core.lss.properties.direct.ChatWindowWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.chat.ChatWindowWidget;
import net.labymod.autogen.core.lss.properties.direct.NewWindowWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.NewWindowWidget;
import net.labymod.autogen.core.lss.properties.direct.InterpolateWidgetDirectPropertyValueAccessor;
import net.labymod.api.client.gui.screen.widget.widgets.transform.InterpolateWidget;
import net.labymod.autogen.core.lss.properties.direct.ChatWindowRendererWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.chat.ChatWindowRendererWidget;
import net.labymod.autogen.core.lss.properties.direct.ChatTabWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.chat.tab.ChatTabWidget;
import net.labymod.autogen.core.lss.properties.direct.SkinLayerWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.customization.SkinLayerWidget;
import net.labymod.autogen.core.lss.properties.direct.PlayerModelWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.customization.PlayerModelWidget;
import net.labymod.autogen.core.lss.properties.direct.SocialPointWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.interaction.social.SocialPointWidget;
import net.labymod.autogen.core.lss.properties.direct.SocialPointRendererWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.interaction.social.SocialPointRendererWidget;
import net.labymod.autogen.core.lss.properties.direct.BulletPointWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.interaction.bullet.BulletPointWidget;
import net.labymod.autogen.core.lss.properties.direct.AbstractPointWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.interaction.AbstractPointWidget;
import net.labymod.autogen.core.lss.properties.direct.BulletPointRendererWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.interaction.bullet.BulletPointRendererWidget;
import net.labymod.autogen.core.lss.properties.direct.AbstractCirclePointWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.interaction.AbstractCirclePointWidget;
import net.labymod.autogen.core.lss.properties.direct.MultilineTextFieldWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.MultilineTextFieldWidget;
import net.labymod.autogen.core.lss.properties.direct.EmoteModelWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.model.EmoteModelWidget;
import net.labymod.autogen.core.lss.properties.direct.CosmeticModelWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.model.CosmeticModelWidget;
import net.labymod.autogen.core.lss.properties.direct.ModelWidgetDirectPropertyValueAccessor;
import net.labymod.api.client.gui.screen.widget.widgets.ModelWidget;
import net.labymod.autogen.core.lss.properties.direct.LabyConnectChatWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.labyconnect.chat.LabyConnectChatWidget;
import net.labymod.autogen.core.lss.properties.direct.LabyConnectChatMessageContentWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.labyconnect.chat.LabyConnectChatMessageContentWidget;
import net.labymod.autogen.core.lss.properties.direct.URIAttachmentWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.labyconnect.chat.attachment.URIAttachmentWidget;
import net.labymod.autogen.core.lss.properties.direct.AttachmentWidgetDirectPropertyValueAccessor;
import net.labymod.api.client.gui.screen.widget.widgets.labyconnect.chat.attachment.AttachmentWidget;
import net.labymod.autogen.core.lss.properties.direct.LabyConnectFriendProfileWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.labyconnect.chat.LabyConnectFriendProfileWidget;
import net.labymod.autogen.core.lss.properties.direct.LabyConnectChatMessageWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.labyconnect.chat.LabyConnectChatMessageWidget;
import net.labymod.autogen.core.lss.properties.direct.ChatHistoryWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.labyconnect.chat.util.ChatHistoryWidget;
import net.labymod.autogen.core.lss.properties.direct.LabyConnectIncomingRequestWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.labyconnect.friends.entries.request.direction.LabyConnectIncomingRequestWidget;
import net.labymod.autogen.core.lss.properties.direct.LabyConnectOutgoingRequestWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.labyconnect.friends.entries.request.direction.LabyConnectOutgoingRequestWidget;
import net.labymod.autogen.core.lss.properties.direct.LabyConnectRequestWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.labyconnect.friends.entries.request.LabyConnectRequestWidget;
import net.labymod.autogen.core.lss.properties.direct.LabyConnectRequestsButtonWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.labyconnect.friends.entries.LabyConnectRequestsButtonWidget;
import net.labymod.autogen.core.lss.properties.direct.LabyConnectFriendWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.labyconnect.friends.entries.LabyConnectFriendWidget;
import net.labymod.autogen.core.lss.properties.direct.LabyConnectEntryWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.labyconnect.friends.LabyConnectEntryWidget;
import net.labymod.autogen.core.lss.properties.direct.NotificationWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.notification.NotificationWidget;
import net.labymod.autogen.core.lss.properties.direct.NotificationStackDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.notification.NotificationStack;
import net.labymod.autogen.core.lss.properties.direct.MainMenuWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.title.MainMenuWidget;
import net.labymod.autogen.core.lss.properties.direct.PanoramaWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.title.background.PanoramaWidget;
import net.labymod.autogen.core.lss.properties.direct.MainMenuButtonsWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.title.ui.MainMenuButtonsWidget;
import net.labymod.autogen.core.lss.properties.direct.SurveysWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.title.ui.SurveysWidget;
import net.labymod.autogen.core.lss.properties.direct.SplashWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.title.header.SplashWidget;
import net.labymod.autogen.core.lss.properties.direct.ModernMinecraftLogoWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.title.header.type.ModernMinecraftLogoWidget;
import net.labymod.autogen.core.lss.properties.direct.LegacyMinecraftLogoWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.title.header.type.LegacyMinecraftLogoWidget;
import net.labymod.autogen.core.lss.properties.direct.MinecraftLogoWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.title.header.MinecraftLogoWidget;
import net.labymod.autogen.core.lss.properties.direct.ModelMinecraftTextWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.title.header.dynamic.ModelMinecraftTextWidget;
import net.labymod.autogen.core.lss.properties.direct.AnimatedMinecraftTextWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.title.header.dynamic.AnimatedMinecraftTextWidget;
import net.labymod.autogen.core.lss.properties.direct.MainOverlayWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.title.overlay.MainOverlayWidget;
import net.labymod.autogen.core.lss.properties.direct.SideAnnouncementWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.widget.widgets.title.overlay.SideAnnouncementWidget;
import net.labymod.autogen.core.lss.properties.direct.ChatSymbolActivityTileComponentWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.ingame.chat.input.tab.ChatSymbolActivity;
import net.labymod.autogen.core.lss.properties.direct.AbstractSidebarActivitySidebarButtonWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.AbstractSidebarActivity;
import net.labymod.autogen.core.lss.properties.direct.ButtonWidgetDirectPropertyValueAccessor;
import net.labymod.api.client.gui.screen.widget.widgets.input.ButtonWidget;
import net.labymod.autogen.core.lss.properties.direct.AddonProfileActivityMiscWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.addons.AddonProfileActivity;
import net.labymod.autogen.core.lss.properties.direct.EmoteOverviewWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.player.widgets.emotes.EmoteOverviewWidget;
import net.labymod.autogen.core.lss.properties.direct.EmotePlaceholderSegmentWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.player.widgets.emotes.EmotePlaceholderSegmentWidget;
import net.labymod.autogen.core.lss.properties.direct.VariableListWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.player.widgets.emotes.VariableListWidget;
import net.labymod.autogen.core.lss.properties.direct.EmoteCustomizationSegmentWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.player.widgets.emotes.EmoteCustomizationSegmentWidget;
import net.labymod.autogen.core.lss.properties.direct.WheelWidgetSegmentDirectPropertyValueAccessor;
import net.labymod.api.client.gui.screen.widget.widgets.WheelWidget;
import net.labymod.autogen.core.lss.properties.direct.SettingLikeWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.player.widgets.SettingLikeWidget;
import net.labymod.autogen.core.lss.properties.direct.HorizontalListWidgetDirectPropertyValueAccessor;
import net.labymod.api.client.gui.screen.widget.widgets.layout.list.HorizontalListWidget;
import net.labymod.autogen.core.lss.properties.direct.ComponentStatusContainerWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.player.widgets.ComponentStatusContainerWidget;
import net.labymod.autogen.core.lss.properties.direct.StatusContainerWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.player.widgets.StatusContainerWidget;
import net.labymod.autogen.core.lss.properties.direct.LastUsedSkinsContainerWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.player.widgets.skin.LastUsedSkinsContainerWidget;
import net.labymod.autogen.core.lss.properties.direct.VerticalListWidgetDirectPropertyValueAccessor;
import net.labymod.api.client.gui.screen.widget.widgets.layout.list.VerticalListWidget;
import net.labymod.autogen.core.lss.properties.direct.SkinPreviewWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.player.widgets.skin.SkinPreviewWidget;
import net.labymod.autogen.core.lss.properties.direct.SkinLayersWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.player.widgets.skin.SkinLayersWidget;
import net.labymod.autogen.core.lss.properties.direct.CosmeticSettingsWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.player.widgets.cosmetics.CosmeticSettingsWidget;
import net.labymod.autogen.core.lss.properties.direct.CosmeticWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.player.widgets.cosmetics.CosmeticWidget;
import net.labymod.autogen.core.lss.properties.direct.ItemPreviewWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.shop.widgets.ItemPreviewWidget;
import net.labymod.autogen.core.lss.properties.direct.SectionedListWidgetSectionWidgetDirectPropertyValueAccessor;
import net.labymod.autogen.core.lss.properties.direct.SectionedListWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.shop.widgets.SectionedListWidget;
import net.labymod.autogen.core.lss.properties.direct.SessionedListWidgetDirectPropertyValueAccessor;
import net.labymod.api.client.gui.screen.widget.widgets.layout.list.SessionedListWidget;
import net.labymod.autogen.core.lss.properties.direct.CosmeticConfigurationWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.shop.widgets.CosmeticConfigurationWidget;
import net.labymod.autogen.core.lss.properties.direct.SquareGridWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.shop.widgets.SquareGridWidget;
import net.labymod.autogen.core.lss.properties.direct.ListWidgetDirectPropertyValueAccessor;
import net.labymod.api.client.gui.screen.widget.widgets.layout.list.ListWidget;
import net.labymod.autogen.core.lss.properties.direct.ShopItemWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.labymod.child.shop.widgets.ShopItemWidget;
import net.labymod.autogen.core.lss.properties.direct.FlexibleContentWidgetDirectPropertyValueAccessor;
import net.labymod.api.client.gui.screen.widget.widgets.layout.FlexibleContentWidget;
import net.labymod.autogen.core.lss.properties.direct.LoadingBarWidgetDirectPropertyValueAccessor;
import net.labymod.core.client.gui.screen.activity.activities.multiplayer.directconnect.LoadingBarWidget;
import net.labymod.autogen.core.lss.properties.direct.SimpleWidgetDirectPropertyValueAccessor;
import net.labymod.api.client.gui.screen.widget.SimpleWidget;
import net.labymod.autogen.core.lss.properties.direct.LabyMarkerWidgetDirectPropertyValueAccessor;
import net.labymod.core.labyconnect.object.marker.LabyMarkerWidget;
import net.labymod.autogen.core.lss.properties.direct.AbstractWidgetDirectPropertyValueAccessor;
import net.labymod.api.client.gui.screen.widget.AbstractWidget;
import net.labymod.autogen.core.lss.properties.direct.StyledWidgetDirectPropertyValueAccessor;
import net.labymod.api.client.gui.screen.widget.StyledWidget;
import net.labymod.api.client.gui.lss.property.DirectPropertyValueAccessor;
import net.labymod.api.client.gui.screen.widget.Widget;
import java.util.Map;
import net.labymod.api.client.gui.lss.property.DirectPropertyValueAccessorRegisterBulk;

public final class CoreLabymod4DirectPropertyValueAccessorRegisterBulk implements DirectPropertyValueAccessorRegisterBulk
{
    @Override
    public void register(final Map<Class<? extends Widget>, DirectPropertyValueAccessor> map) {
        map.put(StyledWidget.class, new StyledWidgetDirectPropertyValueAccessor());
        map.put(AbstractWidget.class, new AbstractWidgetDirectPropertyValueAccessor());
        map.put(LabyMarkerWidget.class, new LabyMarkerWidgetDirectPropertyValueAccessor());
        map.put(SimpleWidget.class, new SimpleWidgetDirectPropertyValueAccessor());
        map.put(LoadingBarWidget.class, new LoadingBarWidgetDirectPropertyValueAccessor());
        map.put(FlexibleContentWidget.class, new FlexibleContentWidgetDirectPropertyValueAccessor());
        map.put(ShopItemWidget.class, new ShopItemWidgetDirectPropertyValueAccessor());
        map.put(ListWidget.class, new ListWidgetDirectPropertyValueAccessor());
        map.put(SquareGridWidget.class, new SquareGridWidgetDirectPropertyValueAccessor());
        map.put(CosmeticConfigurationWidget.class, new CosmeticConfigurationWidgetDirectPropertyValueAccessor());
        map.put(SessionedListWidget.class, new SessionedListWidgetDirectPropertyValueAccessor());
        map.put(SectionedListWidget.class, new SectionedListWidgetDirectPropertyValueAccessor());
        map.put(SectionedListWidget.SectionWidget.class, new SectionedListWidgetSectionWidgetDirectPropertyValueAccessor());
        map.put(ItemPreviewWidget.class, new ItemPreviewWidgetDirectPropertyValueAccessor());
        map.put(CosmeticWidget.class, new CosmeticWidgetDirectPropertyValueAccessor());
        map.put(CosmeticSettingsWidget.class, new CosmeticSettingsWidgetDirectPropertyValueAccessor());
        map.put(SkinLayersWidget.class, new SkinLayersWidgetDirectPropertyValueAccessor());
        map.put(SkinPreviewWidget.class, new SkinPreviewWidgetDirectPropertyValueAccessor());
        map.put(VerticalListWidget.class, new VerticalListWidgetDirectPropertyValueAccessor());
        map.put(LastUsedSkinsContainerWidget.class, new LastUsedSkinsContainerWidgetDirectPropertyValueAccessor());
        map.put(StatusContainerWidget.class, new StatusContainerWidgetDirectPropertyValueAccessor());
        map.put(ComponentStatusContainerWidget.class, new ComponentStatusContainerWidgetDirectPropertyValueAccessor());
        map.put(StatusContainerWidget.class, new StatusContainerWidgetDirectPropertyValueAccessor());
        map.put(HorizontalListWidget.class, new HorizontalListWidgetDirectPropertyValueAccessor());
        map.put(SettingLikeWidget.class, new SettingLikeWidgetDirectPropertyValueAccessor());
        map.put(WheelWidget.Segment.class, new WheelWidgetSegmentDirectPropertyValueAccessor());
        map.put(EmoteCustomizationSegmentWidget.class, new EmoteCustomizationSegmentWidgetDirectPropertyValueAccessor());
        map.put(VariableListWidget.class, new VariableListWidgetDirectPropertyValueAccessor());
        map.put(EmotePlaceholderSegmentWidget.class, new EmotePlaceholderSegmentWidgetDirectPropertyValueAccessor());
        map.put(EmoteOverviewWidget.class, new EmoteOverviewWidgetDirectPropertyValueAccessor());
        map.put(AddonProfileActivity.MiscWidget.class, new AddonProfileActivityMiscWidgetDirectPropertyValueAccessor());
        map.put(ButtonWidget.class, new ButtonWidgetDirectPropertyValueAccessor());
        map.put(AbstractSidebarActivity.SidebarButtonWidget.class, new AbstractSidebarActivitySidebarButtonWidgetDirectPropertyValueAccessor());
        map.put(ChatSymbolActivity.TileComponentWidget.class, new ChatSymbolActivityTileComponentWidgetDirectPropertyValueAccessor());
        map.put(SideAnnouncementWidget.class, new SideAnnouncementWidgetDirectPropertyValueAccessor());
        map.put(MainOverlayWidget.class, new MainOverlayWidgetDirectPropertyValueAccessor());
        map.put(AnimatedMinecraftTextWidget.class, new AnimatedMinecraftTextWidgetDirectPropertyValueAccessor());
        map.put(ModelMinecraftTextWidget.class, new ModelMinecraftTextWidgetDirectPropertyValueAccessor());
        map.put(MinecraftLogoWidget.class, new MinecraftLogoWidgetDirectPropertyValueAccessor());
        map.put(LegacyMinecraftLogoWidget.class, new LegacyMinecraftLogoWidgetDirectPropertyValueAccessor());
        map.put(ModernMinecraftLogoWidget.class, new ModernMinecraftLogoWidgetDirectPropertyValueAccessor());
        map.put(MinecraftLogoWidget.class, new MinecraftLogoWidgetDirectPropertyValueAccessor());
        map.put(SplashWidget.class, new SplashWidgetDirectPropertyValueAccessor());
        map.put(SurveysWidget.class, new SurveysWidgetDirectPropertyValueAccessor());
        map.put(MainMenuButtonsWidget.class, new MainMenuButtonsWidgetDirectPropertyValueAccessor());
        map.put(PanoramaWidget.class, new PanoramaWidgetDirectPropertyValueAccessor());
        map.put(MainMenuWidget.class, new MainMenuWidgetDirectPropertyValueAccessor());
        map.put(NotificationStack.class, new NotificationStackDirectPropertyValueAccessor());
        map.put(NotificationWidget.class, new NotificationWidgetDirectPropertyValueAccessor());
        map.put(LabyConnectEntryWidget.class, new LabyConnectEntryWidgetDirectPropertyValueAccessor());
        map.put(LabyConnectFriendWidget.class, new LabyConnectFriendWidgetDirectPropertyValueAccessor());
        map.put(LabyConnectRequestsButtonWidget.class, new LabyConnectRequestsButtonWidgetDirectPropertyValueAccessor());
        map.put(LabyConnectRequestWidget.class, new LabyConnectRequestWidgetDirectPropertyValueAccessor());
        map.put(LabyConnectOutgoingRequestWidget.class, new LabyConnectOutgoingRequestWidgetDirectPropertyValueAccessor());
        map.put(LabyConnectIncomingRequestWidget.class, new LabyConnectIncomingRequestWidgetDirectPropertyValueAccessor());
        map.put(ChatHistoryWidget.class, new ChatHistoryWidgetDirectPropertyValueAccessor());
        map.put(LabyConnectChatMessageWidget.class, new LabyConnectChatMessageWidgetDirectPropertyValueAccessor());
        map.put(LabyConnectFriendProfileWidget.class, new LabyConnectFriendProfileWidgetDirectPropertyValueAccessor());
        map.put(AttachmentWidget.class, new AttachmentWidgetDirectPropertyValueAccessor());
        map.put(URIAttachmentWidget.class, new URIAttachmentWidgetDirectPropertyValueAccessor());
        map.put(LabyConnectChatMessageContentWidget.class, new LabyConnectChatMessageContentWidgetDirectPropertyValueAccessor());
        map.put(LabyConnectChatWidget.class, new LabyConnectChatWidgetDirectPropertyValueAccessor());
        map.put(ModelWidget.class, new ModelWidgetDirectPropertyValueAccessor());
        map.put(CosmeticModelWidget.class, new CosmeticModelWidgetDirectPropertyValueAccessor());
        map.put(EmoteModelWidget.class, new EmoteModelWidgetDirectPropertyValueAccessor());
        map.put(MultilineTextFieldWidget.class, new MultilineTextFieldWidgetDirectPropertyValueAccessor());
        map.put(AbstractCirclePointWidget.class, new AbstractCirclePointWidgetDirectPropertyValueAccessor());
        map.put(BulletPointRendererWidget.class, new BulletPointRendererWidgetDirectPropertyValueAccessor());
        map.put(AbstractPointWidget.class, new AbstractPointWidgetDirectPropertyValueAccessor());
        map.put(BulletPointWidget.class, new BulletPointWidgetDirectPropertyValueAccessor());
        map.put(AbstractPointWidget.class, new AbstractPointWidgetDirectPropertyValueAccessor());
        map.put(SocialPointRendererWidget.class, new SocialPointRendererWidgetDirectPropertyValueAccessor());
        map.put(SocialPointWidget.class, new SocialPointWidgetDirectPropertyValueAccessor());
        map.put(PlayerModelWidget.class, new PlayerModelWidgetDirectPropertyValueAccessor());
        map.put(SkinLayerWidget.class, new SkinLayerWidgetDirectPropertyValueAccessor());
        map.put(ChatTabWidget.class, new ChatTabWidgetDirectPropertyValueAccessor());
        map.put(ChatWindowRendererWidget.class, new ChatWindowRendererWidgetDirectPropertyValueAccessor());
        map.put(InterpolateWidget.class, new InterpolateWidgetDirectPropertyValueAccessor());
        map.put(NewWindowWidget.class, new NewWindowWidgetDirectPropertyValueAccessor());
        map.put(ChatWindowWidget.class, new ChatWindowWidgetDirectPropertyValueAccessor());
        map.put(GradientWidget.class, new GradientWidgetDirectPropertyValueAccessor());
        map.put(StoreItemWidget.class, new StoreItemWidgetDirectPropertyValueAccessor());
        map.put(ChangelogWidget.class, new ChangelogWidgetDirectPropertyValueAccessor());
        map.put(ProfileInfoWidget.class, new ProfileInfoWidgetDirectPropertyValueAccessor());
        map.put(DescriptionWidget.class, new DescriptionWidgetDirectPropertyValueAccessor());
        map.put(ReviewWidget.class, new ReviewWidgetDirectPropertyValueAccessor());
        map.put(InstalledItemWidget.class, new InstalledItemWidgetDirectPropertyValueAccessor());
        map.put(ServerEntryWidget.class, new ServerEntryWidgetDirectPropertyValueAccessor());
        map.put(ServerFolderWidget.class, new ServerFolderWidgetDirectPropertyValueAccessor());
        map.put(ServerInfoWidget.class, new ServerInfoWidgetDirectPropertyValueAccessor());
        map.put(LanServerInfoWidget.class, new LanServerInfoWidgetDirectPropertyValueAccessor());
        map.put(LabyNetServerInfoWidget.class, new LabyNetServerInfoWidgetDirectPropertyValueAccessor());
        map.put(LiveLabyNetServerInfoWidget.class, new LiveLabyNetServerInfoWidgetDirectPropertyValueAccessor());
        map.put(DirectConnectServerInfoWidget.class, new DirectConnectServerInfoWidgetDirectPropertyValueAccessor());
        map.put(StorageServerInfoWidget.class, new StorageServerInfoWidgetDirectPropertyValueAccessor());
        map.put(LiveLabyNetServerInfoWidget.class, new LiveLabyNetServerInfoWidgetDirectPropertyValueAccessor());
        map.put(LabyNetServerInfoWidget.class, new LabyNetServerInfoWidgetDirectPropertyValueAccessor());
        map.put(PublicServerInfoWidget.class, new PublicServerInfoWidgetDirectPropertyValueAccessor());
        map.put(ScreenshotViewerWidget.class, new ScreenshotViewerWidgetDirectPropertyValueAccessor());
        map.put(ImageViewerWidget.class, new ImageViewerWidgetDirectPropertyValueAccessor());
        map.put(ScreenshotSectionWidget.class, new ScreenshotSectionWidgetDirectPropertyValueAccessor());
        map.put(ScreenshotScrollbarWidget.class, new ScreenshotScrollbarWidgetDirectPropertyValueAccessor());
        map.put(ScreenshotTimelineWidget.class, new ScreenshotTimelineWidgetDirectPropertyValueAccessor());
        map.put(ScreenshotContainerWidget.class, new ScreenshotContainerWidgetDirectPropertyValueAccessor());
        map.put(ScreenshotTileWidget.class, new ScreenshotTileWidgetDirectPropertyValueAccessor());
        map.put(GlobalSettingWidget.class, new GlobalSettingWidgetDirectPropertyValueAccessor());
        map.put(HudWidgetRendererWidget.class, new HudWidgetRendererWidgetDirectPropertyValueAccessor());
        map.put(HudWidgetInteractionWidget.class, new HudWidgetInteractionWidgetDirectPropertyValueAccessor());
        map.put(HudWidgetRendererWidget.class, new HudWidgetRendererWidgetDirectPropertyValueAccessor());
        map.put(HudWidgetTilesGridWidget.class, new HudWidgetTilesGridWidgetDirectPropertyValueAccessor());
        map.put(HudWidgetTypeInfoWidget.class, new HudWidgetTypeInfoWidgetDirectPropertyValueAccessor());
        map.put(HudWidgetWindowWidget.class, new HudWidgetWindowWidgetDirectPropertyValueAccessor());
        map.put(NavigationListWidget.class, new NavigationListWidgetDirectPropertyValueAccessor());
        map.put(WheelWidget.class, new WheelWidgetDirectPropertyValueAccessor());
        map.put(EmoteWheelWidget.class, new EmoteWheelWidgetDirectPropertyValueAccessor());
        map.put(EmoteSegmentWidget.class, new EmoteSegmentWidgetDirectPropertyValueAccessor());
        map.put(RevisionPopupWidget.class, new RevisionPopupWidgetDirectPropertyValueAccessor());
        map.put(AccountPopupEntryWidget.class, new AccountPopupEntryWidgetDirectPropertyValueAccessor());
        map.put(AccountWidget.class, new AccountWidgetDirectPropertyValueAccessor());
        map.put(NewWindowWidget.class, new NewWindowWidgetDirectPropertyValueAccessor());
        map.put(SprayWheelWidget.class, new SprayWheelWidgetDirectPropertyValueAccessor());
        map.put(AddonRecommendationPacketHandler.AddonRecommendationItemWidget.class, new AddonRecommendationPacketHandlerAddonRecommendationItemWidgetDirectPropertyValueAccessor());
        map.put(StyleOrderTestWidget.class, new StyleOrderTestWidgetDirectPropertyValueAccessor());
        map.put(LazyGridWidgetTestActivity.DummyWidget.class, new LazyGridWidgetTestActivityDummyWidgetDirectPropertyValueAccessor());
    }
}
